version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=indexify
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./:/app
    depends_on:
      neo4j:
        condition: service_healthy
    command: python workflow.py
    deploy:
      restart_policy:
        condition: none

  neo4j:
    image: neo4j:4.4
    environment:
      - NEO4J_AUTH=neo4j/indexify
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    healthcheck:
      test: ["CMD", "neo4j", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  neo4j_data:
